package com.npms.core.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * A work-item / ticket within a project.
 * Created by PMC or PM; assigned to OA for execution.
 *
 * Ticket lifecycle:
 *   OPEN → IN_PROGRESS → AWAITING_REVIEW → RESOLVED → CLOSED
 *
 * MD can REOPEN a CLOSED or RESOLVED ticket (mandatory reopen_reason).
 * Escalation path: OA → PM → PMC → MD.
 */
@Entity
@Table(name = "project_ticket", schema = "public")
public class ProjectTicket {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "header_id", nullable = false)
    private Long headerId;

    /**
     * Unique human-readable ticket code, generated by TicketService.
     * Format: TKT-YYYY-NNNNNN  e.g. TKT-2026-000001
     */
    @Column(name = "ticket_code", nullable = false, unique = true)
    private String ticketCode;

    @Column(name = "title", nullable = false, columnDefinition = "TEXT")
    private String title;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * NICSI Work-Item Categories:
     * PO_FOLLOW_UP | BILL_SUBMISSION | RECEIPT_PENDING | GST_INVOICE
     * VENDOR_REMINDER | PENALTY_WAIVER | EXPIRY_RENEWAL | COMPLIANCE_AUDIT
     * SITE_VISIT | CLIENT_COORDINATION | INTERNAL_APPROVAL | NICSI_HOLD_RELEASE | GENERAL
     */
    @Column(name = "ticket_type", nullable = false)
    private String ticketType = "PO_FOLLOW_UP";

    /** LOW | MEDIUM | HIGH | CRITICAL */
    @Column(name = "priority", nullable = false)
    private String priority = "MEDIUM";

    /** OPEN | IN_PROGRESS | AWAITING_REVIEW | RESOLVED | CLOSED | REOPENED */
    @Column(name = "status", nullable = false)
    private String status = "OPEN";

    @Column(name = "created_by", nullable = false)
    private String createdBy;

    /** OA username this ticket is assigned to. */
    @Column(name = "assigned_to")
    private String assignedTo;

    /** PM username who reviews and closes the ticket. */
    @Column(name = "reviewed_by")
    private String reviewedBy;

    /** PMC or MD username if the ticket has been escalated. */
    @Column(name = "escalated_to")
    private String escalatedTo;

    /** SLA in hours from creation to expected resolution. */
    @Column(name = "sla_hours", nullable = false)
    private Integer slaHours = 48;

    @Column(name = "sla_deadline")
    private LocalDateTime slaDeadline;

    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;

    @Column(name = "closed_at")
    private LocalDateTime closedAt;

    /**
     * Mandatory when MD reopens a CLOSED/RESOLVED ticket.
     * Stored here AND in ticket_event for auditability.
     */
    @Column(name = "reopen_reason", columnDefinition = "TEXT")
    private String reopenReason;

    /**
     * Lifecycle stage this ticket is associated with.
     * E.g. "BILL_SUBMITTED" — ticket to chase a vendor invoice.
     */
    @Column(name = "stage_ref")
    private String stageRef;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    @Transient
    public boolean isOverdue() {
        return slaDeadline != null
                && LocalDateTime.now().isAfter(slaDeadline)
                && !"RESOLVED".equals(status)
                && !"CLOSED".equals(status);
    }

    // ── Getters & Setters ──────────────────────────────────────────────────

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Long getHeaderId() { return headerId; }
    public void setHeaderId(Long headerId) { this.headerId = headerId; }

    public String getTicketCode() { return ticketCode; }
    public void setTicketCode(String ticketCode) { this.ticketCode = ticketCode; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getTicketType() { return ticketType; }
    public void setTicketType(String ticketType) { this.ticketType = ticketType; }

    public String getPriority() { return priority; }
    public void setPriority(String priority) { this.priority = priority; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getCreatedBy() { return createdBy; }
    public void setCreatedBy(String createdBy) { this.createdBy = createdBy; }

    public String getAssignedTo() { return assignedTo; }
    public void setAssignedTo(String assignedTo) { this.assignedTo = assignedTo; }

    public String getReviewedBy() { return reviewedBy; }
    public void setReviewedBy(String reviewedBy) { this.reviewedBy = reviewedBy; }

    public String getEscalatedTo() { return escalatedTo; }
    public void setEscalatedTo(String escalatedTo) { this.escalatedTo = escalatedTo; }

    public Integer getSlaHours() { return slaHours; }
    public void setSlaHours(Integer slaHours) { this.slaHours = slaHours; }

    public LocalDateTime getSlaDeadline() { return slaDeadline; }
    public void setSlaDeadline(LocalDateTime slaDeadline) { this.slaDeadline = slaDeadline; }

    public LocalDateTime getResolvedAt() { return resolvedAt; }
    public void setResolvedAt(LocalDateTime resolvedAt) { this.resolvedAt = resolvedAt; }

    public LocalDateTime getClosedAt() { return closedAt; }
    public void setClosedAt(LocalDateTime closedAt) { this.closedAt = closedAt; }

    public String getReopenReason() { return reopenReason; }
    public void setReopenReason(String reopenReason) { this.reopenReason = reopenReason; }

    public String getStageRef() { return stageRef; }
    public void setStageRef(String stageRef) { this.stageRef = stageRef; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
